
import {
  FaHourglassEnd,
  FaRegCreditCard,
  FaSignal,
  FaSlack,
  FaUserGraduate,
  FaUsers,
  FaUserShield,
} from "react-icons/fa";
import { FaUserGear, FaUsersViewfinder } from "react-icons/fa6";
import {
  AdminPage,
  Students,
  OneStudent,
  Speciality,
  PaymentHistory,
  TransactionHistory,
  PaymentDetails,
  StudentStatistics,
  PmGroupController,
  OnePaymentGroup,
  GroupStatistics,
  GroupList,
  GroupStudents,
  Role,
} from "@modules";




export const routesConfig = [
  {
    path: "super-admin-panel/role",
    label: "Rol va ruxsatlar",
    icon: <FaUserGear style={{ fontSize: "22px" }} />,
    element: <Role />,
    permissions: ["ADMIN_ROLE_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/admin-page",
    label: "Admin User",
    icon: <FaUserShield style={{ fontSize: "22px" }} />,
    element: <AdminPage />,
    permissions: ["ADMIN_USER_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/students",
    label: "Studentlar",
    icon: <FaUserGraduate style={{ fontSize: "22px" }} />,
    element: <Students />,
    permissions: ["STUDENT_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/students/:id",
    element: <OneStudent />,
    permissions: ["STUDENT_MENU"],
    showInSidebar: false,
  },
  {
    path: "super-admin-panel/speciality",
    label: "Yo'nalishlar",
    icon: <FaSlack style={{ fontSize: "22px" }} />,
    element: <Speciality />,
    permissions: ["SPECIALITY_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/group-list",
    label: "Guruhlar ro'yxati",
    icon: <FaUsers style={{ fontSize: "22px" }} />,
    element: <GroupList />,
    permissions: ["GROUP_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/pmgroup-controller",
    label: "To'lov guruhlari",
    icon: <FaUsersViewfinder style={{ fontSize: "22px" }} />,
    element: <PmGroupController />,
    permissions: ["PAYMENT_GROUP_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/pmgroup-controller/:id",
    element: <OnePaymentGroup />,
    permissions: ["PAYMENT_GROUP_MENU"],
    showInSidebar: false,
  },
  {
    path: "super-admin-panel/payment-history",
    label: "Click",
    icon: <FaRegCreditCard style={{ fontSize: "22px" }} />,
    element: <PaymentHistory />,
    permissions: ["PAYMENT_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/transaction-history",
    label: "Tranzaksiyalar ro'yxati",
    icon: <FaHourglassEnd style={{ fontSize: "22px" }} />,
    element: <TransactionHistory />,
    permissions: ["TRANSACTION_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/transaction-history/:id",
    element: <PaymentDetails />,
    permissions: ["TRANSACTION_MENU"],
    showInSidebar: false,
  },
  {
    path: "super-admin-panel/students-statistics",
    label: "Studentlar statistikasi",
    icon: <FaSignal style={{ fontSize: "22px" }} />,
    element: <StudentStatistics />,
    permissions: ["STUDENT_STATISTICS_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/group-statistics",
    label: "Guruhlar statistikasi",
    icon: <FaSignal style={{ fontSize: "22px" }} />,
    element: <GroupStatistics />,
    permissions: ["GROUP_STATISTICS_MENU"],
    showInSidebar: true,
  },
  {
    path: "super-admin-panel/group-statistics/:id",
    element: <GroupStudents />,
    permissions: ["GROUP_STATISTICS_MENU"],
    showInSidebar: false,
  },
];
